### ISSUE TITLE
Estruturar Backend

### ISSUE THREAD

**Issue by JoaoRafa19** [ICEI-PUC-Minas-PCO-ADS-TI/2025-1-p3-tiapn-tiapn-grupo-2-de-si#5]
# Tarefa: Configuração Inicial do Backend com Go, Gin e Docker

## Objetivo
Criar a estrutura base do backend utilizando Go, Gin Framework e Docker, configurando ambiente de desenvolvimento e integração com MySQL.

---

### 1. Estrutura de Diretórios
```bash
backend/
├── cmd/
│   └── main.go
├── internal/
│   ├── config/
│   ├── routes/
│   ├── controllers/
│   ├── models/
│   └── middleware/
├── pkg/
├── Dockerfile
├── docker-compose.yml
├── go.mod
├── go.sum
└── .env
```

### 2. Inicialização do Projeto Go
```bash
mkdir -p backend/cmd backend/internal/{config,routes,controllers,models,middleware}
cd backend
go mod init nutri-insulin-control/backend
```

### 3. Instalação de Dependências
```bash
go get -u \
  github.com/gin-gonic/gin \
  github.com/jinzhu/gorm \
  github.com/go-sql-driver/mysql \
  github.com/joho/godotenv
```

### 4. Configuração do Docker

**Dockerfile:**
```dockerfile
# Estágio de construção
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /nutri-app ./cmd/main.go

# Estágio de produção
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /nutri-app .
COPY --from=builder /app/.env .
EXPOSE 8080
CMD ["./nutri-app"]
```

**docker-compose.yml:**
```yaml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - nutri-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nutri_db
      MYSQL_USER: nutri_user
      MYSQL_PASSWORD: nutri_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nutri-network

volumes:
  mysql-data:

networks:
  nutri-network:
```

### 5. Configuração de Ambiente (.env)
```env
APP_PORT=8080
DB_HOST=mysql
DB_PORT=3306
DB_USER=nutri_user
DB_PASSWORD=nutri_pass
DB_NAME=nutri_db
```

### 6. Código Inicial (main.go)
```go
package main

import (
	"log"
	"net/http"
	"os"
	
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/joho/godotenv"
)

func main() {
	// Carregar variáveis de ambiente
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	// Configurar Gin
	router := gin.Default()
	
	// Configurar middlewares
	router.Use(gin.Logger())
	router.Use(gin.Recovery())

	// Health Check
	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status":  "ok",
			"version": "1.0.0",
		})
	})

	// Inicializar banco de dados
	db := initDB()
	defer db.Close()

	// Iniciar servidor
	port := os.Getenv("APP_PORT")
	router.Run(":" + port)
}

func initDB() *gorm.DB {
	connectionString := os.Getenv("DB_USER") + ":" + os.Getenv("DB_PASSWORD") + 
		"@tcp(" + os.Getenv("DB_HOST") + ":" + os.Getenv("DB_PORT") + ")/" + 
		os.Getenv("DB_NAME") + "?charset=utf8&parseTime=True&loc=Local"

	db, err := gorm.Open("mysql", connectionString)
	if err != nil {
		log.Fatal("Failed to connect database: ", err)
	}

	log.Println("Database connection established")
	return db
}
```

---

## Critérios de Aceitação
✅ Servidor responde em `http://localhost:8080/health`  
✅ Conexão com MySQL estabelecida via Docker  
✅ Build do Docker completa sem erros  
✅ Ambiente configurado via variáveis .env  
✅ Estrutura de diretórios conforme definição  

---

## Comandos para Execução
```bash
# Construir e iniciar containers
docker-compose up --build

# Verificar logs
docker-compose logs -f backend

# Testar health check
curl http://localhost:8080/health
```

---
